version: "3"

services:
  ml-inference:
    build:
      context: ./api  
      dockerfile: Dockerfile  
    image: ml-inference
    container_name: ml-inference
    # platform: linux/arm64
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
      - ./tmp:/tmp
    environment:
      - EOTDL_DOWNLOAD_PATH=/tmp
    env_file: 
      - .env
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000