version: "3"

services:
  ml-inference:
    image: earthpulseit/ml-inference
    container_name: ml-inference
    # platform: linux/arm64
    ports:
      - 8000:8000
    volumes:
      - ./tmp:/tmp
    environment:
      - EOTDL_DOWNLOAD_PATH=/tmp
    env_file: 
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000